spring:
  application:
    name: card-service
  main:
    allow-circular-references: true
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        # default_schema: cards
        dialect: org.hibernate.dialect.MySQL8Dialect
    database: mysql
    database-platform: org.hibernate.dialect.MySQL8Dialect
  generate-ddl: true
  properties:
    hibernate:
      format_sql: true
      jdbc:
        time_zone: Africa/Nairobi
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/cards?useSSL=true
    username: root
    password: root
    hikari:
      minimum-idle: 1
      maximum-pool-size: 10
      connection-timeout: 60000
      idle-timeout: 300000
      max-lifetime: 600000
      validation-timeout: 5000
      pool-name: cards-service
      leak-detection-threshold: 60000
      keepalive-time: 30000
    driver-class-name: com.mysql.cj.jdbc.Driver

token:
  signing:
    key: 78076ECCEF61473C9D575E3A1AB668B278076ECCEF61473C9D575E3A1AB668B2
server:
  servlet:
    context-path: /cards
