package com.logicea.cards.services;

import com.logicea.cards.dto.CardDto;
import com.logicea.cards.dto.CardResponse;
import com.logicea.cards.dto.SearchDto;
import com.logicea.cards.models.Users;

import java.util.List;

public interface CardService {
    /**
     * Saves a new card
     *
     * @param user
     * @param card {{@link  CardDto }} holds information entered by the user
     * @return {{@link }} Information entered by the user & other information generated by the DB
     */
    CardResponse<CardDto> saveCard(Users user, CardDto card);

    /**
     * Updates card information
     *
     * @param id   - Card unique identifier
     * @param card - New card information
     * @return {{@link }} new card information
     */
    CardResponse<CardDto> saveCard(long id,Users user, CardDto card);

    /**
     * Soft deletes a card from the DB
     *
     * @param id - Card unique identifier
     */
    CardResponse<CardDto> deleteCard(long id);

    CardResponse<List<CardDto>> search(Users user, SearchDto searchDto);

    boolean getCarByNameAndUser(String colour, long id);
}
